# Mapping of all 114 Surahs with transliterated names, English translations, verse counts, and search aliases.

SURAHS = [
    {"id": 1, "name": "Al-Fatihah", "english": "The Opening", "verses": 7, "aliases": ["fatihah", "opening", "theopening", "alfatihah"]},
    {"id": 2, "name": "Al-Baqarah", "english": "The Cow", "verses": 286, "aliases": ["baqarah", "cow", "thecow", "albaqarah"]},
    {"id": 3, "name": "Ali 'Imran", "english": "Family of Imran", "verses": 200, "aliases": ["imran", "familyofimran", "aliimran", "aalimran", "ali-imran"]},
    {"id": 4, "name": "An-Nisa", "english": "The Women", "verses": 176, "aliases": ["nisa", "women", "thewomen", "annisa"]},
    {"id": 5, "name": "Al-Ma'idah", "english": "The Table Spread", "verses": 120, "aliases": ["maidah", "table", "tablespread", "thetablespread", "almaidah"]},
    {"id": 6, "name": "Al-An'am", "english": "The Cattle", "verses": 165, "aliases": ["anam", "cattle", "thecattle", "alanam"]},
    {"id": 7, "name": "Al-A'raf", "english": "The Heights", "verses": 206, "aliases": ["araf", "heights", "theheights", "alaraf"]},
    {"id": 8, "name": "Al-Anfal", "english": "The Spoils of War", "verses": 75, "aliases": ["anfal", "spoils", "spoilsofwar", "thespoilsofwar", "alanfal"]},
    {"id": 9, "name": "At-Tawbah", "english": "The Repentance", "verses": 129, "aliases": ["tawbah", "repentance", "therepentance", "attawbah", "baraah"]},
    {"id": 10, "name": "Yunus", "english": "Jonah", "verses": 109, "aliases": ["yunus", "jonah"]},
    {"id": 11, "name": "Hud", "english": "Hud", "verses": 123, "aliases": ["hud"]},
    {"id": 12, "name": "Yusuf", "english": "Joseph", "verses": 111, "aliases": ["yusuf", "joseph"]},
    {"id": 13, "name": "Ar-Ra'd", "english": "The Thunder", "verses": 43, "aliases": ["rad", "thunder", "thethunder", "arrad"]},
    {"id": 14, "name": "Ibrahim", "english": "Abraham", "verses": 52, "aliases": ["ibrahim", "abraham"]},
    {"id": 15, "name": "Al-Hijr", "english": "The Rocky Tract", "verses": 99, "aliases": ["hijr", "rocky", "rockytract", "stoneland", "thestoneland", "alhijr"]},
    {"id": 16, "name": "An-Nahl", "english": "The Bee", "verses": 128, "aliases": ["nahl", "bee", "thebee", "annahl"]},
    {"id": 17, "name": "Al-Isra", "english": "The Night Journey", "verses": 111, "aliases": ["isra", "nightjourney", "thenightjourney", "alisra", "subhan", "baniisrail", "childrenofisrael"]},
    {"id": 18, "name": "Al-Kahf", "english": "The Cave", "verses": 110, "aliases": ["kahf", "cave", "thecave", "alkahf"]},
    {"id": 19, "name": "Maryam", "english": "Mary", "verses": 98, "aliases": ["maryam", "mary"]},
    {"id": 20, "name": "Ta-Ha", "english": "Ta-Ha", "verses": 135, "aliases": ["taha"]},
    {"id": 21, "name": "Al-Anbiya", "english": "The Prophets", "verses": 112, "aliases": ["anbiya", "prophets", "theprophets", "alanbiya"]},
    {"id": 22, "name": "Al-Hajj", "english": "The Pilgrimage", "verses": 78, "aliases": ["hajj", "pilgrimage", "thepilgrimage", "alhajj"]},
    {"id": 23, "name": "Al-Mu'minun", "english": "The Believers", "verses": 118, "aliases": ["muminun", "believers", "thebelievers", "almuminun"]},
    {"id": 24, "name": "An-Nur", "english": "The Light", "verses": 64, "aliases": ["nur", "light", "thelight", "annur"]},
    {"id": 25, "name": "Al-Furqan", "english": "The Criterion", "verses": 77, "aliases": ["furqan", "criterion", "thecriterion", "alfurqan"]},
    {"id": 26, "name": "Ash-Shu'ara", "english": "The Poets", "verses": 227, "aliases": ["shuara", "poets", "thepoets", "ashshuara"]},
    {"id": 27, "name": "An-Naml", "english": "The Ant", "verses": 93, "aliases": ["naml", "ant", "theant", "annaml"]},
    {"id": 28, "name": "Al-Qasas", "english": "The Stories", "verses": 88, "aliases": ["qasas", "stories", "thestories", "alqasas"]},
    {"id": 29, "name": "Al-Ankabut", "english": "The Spider", "verses": 69, "aliases": ["ankabut", "spider", "thespider", "alankabut"]},
    {"id": 30, "name": "Ar-Rum", "english": "The Romans", "verses": 60, "aliases": ["rum", "romans", "theromans", "arrum", "rome", "therome"]},
    {"id": 31, "name": "Luqman", "english": "Luqman", "verses": 34, "aliases": ["luqman"]},
    {"id": 32, "name": "As-Sajdah", "english": "The Prostration", "verses": 30, "aliases": ["sajdah", "prostration", "theprostration", "assajdah"]},
    {"id": 33, "name": "Al-Ahzab", "english": "The Combined Forces", "verses": 73, "aliases": ["ahzab", "combinedforces", "thecombinedforces", "allies", "theallies", "clans", "theclans", "alahzab"]},
    {"id": 34, "name": "Saba", "english": "Sheba", "verses": 54, "aliases": ["saba", "sheba"]},
    {"id": 35, "name": "Fatir", "english": "Originator", "verses": 45, "aliases": ["fatir", "originator", "creator", "thecreator", "malaikah", "angels", "theangels"]},
    {"id": 36, "name": "Ya-Sin", "english": "Ya-Sin", "verses": 83, "aliases": ["yasin", "yasheen"]},
    {"id": 37, "name": "As-Saffat", "english": "Those who set the Ranks", "verses": 182, "aliases": ["saffat", "ranks", "thosewhosettheranks", "thosearrangedinranks", "assaffat"]},
    {"id": 38, "name": "Sad", "english": "The Letter Sad", "verses": 88, "aliases": ["sad"]},
    {"id": 39, "name": "Az-Zumar", "english": "The Troops", "verses": 75, "aliases": ["zumar", "troops", "thetroops", "crowds", "thecrowds", "groups", "thegroups", "azzumar"]},
    {"id": 40, "name": "Ghafir", "english": "The Forgiver", "verses": 85, "aliases": ["ghafir", "forgiver", "theforgiver", "mumin", "believer", "thebeliever"]},
    {"id": 41, "name": "Fussilat", "english": "Explained in Detail", "verses": 54, "aliases": ["fussilat", "explainedindetail", "hamimsajdah"]},
    {"id": 42, "name": "Ash-Shura", "english": "The Consultation", "verses": 53, "aliases": ["shura", "consultation", "theconsultation", "council", "thecouncil", "ashshura"]},
    {"id": 43, "name": "Az-Zukhruf", "english": "The Ornaments of Gold", "verses": 89, "aliases": ["zukhruf", "ornaments", "ornamentsofgold", "goldornaments", "azzukhruf"]},
    {"id": 44, "name": "Ad-Dukhan", "english": "The Smoke", "verses": 59, "aliases": ["dukhan", "smoke", "thesmoke", "addukhan"]},
    {"id": 45, "name": "Al-Jathiyah", "english": "The Crouching", "verses": 37, "aliases": ["jathiyah", "crouching", "thecrouching", "kneeling", "thekneeling", "aljathiyah"]},
    {"id": 46, "name": "Al-Ahqaf", "english": "The Wind-Curved Sandhills", "verses": 35, "aliases": ["ahqaf", "windcurvedsandhills", "sandhills", "thesandhills", "alahqaf"]},
    {"id": 47, "name": "Muhammad", "english": "Muhammad", "verses": 38, "aliases": ["muhammad"]},
    {"id": 48, "name": "Al-Fath", "english": "The Victory", "verses": 29, "aliases": ["fath", "victory", "thevictory", "alfath"]},
    {"id": 49, "name": "Al-Hujurat", "english": "The Dwellings", "verses": 18, "aliases": ["hujurat", "dwellings", "thedwellings", "chambers", "thechambers", "privatechambers", "alhujurat"]},
    {"id": 50, "name": "Qaf", "english": "The Letter Qaf", "verses": 45, "aliases": ["qaf"]},
    {"id": 51, "name": "Adh-Dhariyat", "english": "The Winnowing Winds", "verses": 60, "aliases": ["dhariyat", "winnowingwinds", "winds", "thedustscatteringwinds", "adhdhariyat"]},
    {"id": 52, "name": "At-Tur", "english": "The Mount", "verses": 49, "aliases": ["tur", "mount", "themount", "attur"]},
    {"id": 53, "name": "An-Najm", "english": "The Star", "verses": 62, "aliases": ["najm", "star", "thestar", "annajm"]},
    {"id": 54, "name": "Al-Qamar", "english": "The Moon", "verses": 55, "aliases": ["qamar", "moon", "themoon", "alqamar"]},
    {"id": 55, "name": "Ar-Rahman", "english": "The Beneficent", "verses": 78, "aliases": ["rahman", "beneficent", "merciful", "themerciful", "theentirelymerciful", "thebeneficent", "arrahman"]},
    {"id": 56, "name": "Al-Waqi'ah", "english": "The Inevitable", "verses": 96, "aliases": ["waqiah", "inevitable", "theinevitable", "theevent", "alwaqiah"]},
    {"id": 57, "name": "Al-Hadid", "english": "The Iron", "verses": 29, "aliases": ["hadid", "iron", "theiron", "alhadid"]},
    {"id": 58, "name": "Al-Mujadilah", "english": "The Pleading Woman", "verses": 22, "aliases": ["mujadilah", "pleading", "pleadingwoman", "shethatdisputes", "thepleadingwoman", "almujadilah"]},
    {"id": 59, "name": "Al-Hashr", "english": "The Exile", "verses": 24, "aliases": ["hashr", "exile", "banishment", "gathering", "thegathering", "theexile", "alhashr"]},
    {"id": 60, "name": "Al-Mumtahanah", "english": "She that is to be examined", "verses": 13, "aliases": ["mumtahanah", "shethatistobeexamined", "examined", "thewomanexamined", "almumtahanah"]},
    {"id": 61, "name": "As-Saff", "english": "The Ranks", "verses": 14, "aliases": ["saff", "ranks", "battlearray", "theranks", "assaff"]},
    {"id": 62, "name": "Al-Jumu'ah", "english": "The Congregation", "verses": 11, "aliases": ["jumuah", "congregation", "friday", "thecongregation", "aljumuah"]},
    {"id": 63, "name": "Al-Munafiqun", "english": "The Hypocrites", "verses": 11, "aliases": ["munafiqun", "hypocrites", "thehypocrites", "almunafiqun"]},
    {"id": 64, "name": "At-Taghabun", "english": "The Mutual Disillusion", "verses": 18, "aliases": ["taghabun", "mutualdisillusion", "mutualdeprivation", "lossandgain", "attaghabun"]},
    {"id": 65, "name": "At-Talaq", "english": "The Divorce", "verses": 12, "aliases": ["talaq", "divorce", "thedivorce", "attalaq"]},
    {"id": 66, "name": "At-Tahrim", "english": "The Prohibition", "verses": 12, "aliases": ["tahrim", "prohibition", "theprohibition", "attahrim"]},
    {"id": 67, "name": "Al-Mulk", "english": "The Sovereignty", "verses": 30, "aliases": ["mulk", "sovereignty", "dominion", "thedominion", "kingdom", "thekingdom", "control", "almulk"]},
    {"id": 68, "name": "Al-Qalam", "english": "The Pen", "verses": 52, "aliases": ["qalam", "pen", "thepen", "alqalam", "nun"]},
    {"id": 69, "name": "Al-Haqqah", "english": "The Reality", "verses": 52, "aliases": ["haqqah", "reality", "theinevitablereality", "thetruth", "theindubitabletruth", "alhaqqah"]},
    {"id": 70, "name": "Al-Ma'arij", "english": "The Ascending Stairways", "verses": 44, "aliases": ["maarij", "ascendingstairways", "waysofascent", "theascendingstairways", "almaarij"]},
    {"id": 71, "name": "Nuh", "english": "Noah", "verses": 28, "aliases": ["nuh", "noah"]},
    {"id": 72, "name": "Al-Jinn", "english": "The Jinn", "verses": 28, "aliases": ["jinn", "thejinn", "aljinn"]},
    {"id": 73, "name": "Al-Muzzammil", "english": "The Enshrouded One", "verses": 20, "aliases": ["muzzammil", "enshroudedone", "wrappedingarments", "theenshroudedone", "almuzzammil"]},
    {"id": 74, "name": "Al-Muddaththir", "english": "The Cloaked One", "verses": 56, "aliases": ["muddaththir", "cloakedone", "thecloakedone", "theoneenwrapped", "almuddaththir"]},
    {"id": 75, "name": "Al-Qiyamah", "english": "The Resurrection", "verses": 40, "aliases": ["qiyamah", "resurrection", "theresurrection", "alqiyamah"]},
    {"id": 76, "name": "Al-Insan", "english": "The Man", "verses": 31, "aliases": ["insan", "man", "human", "time", "theman", "alinsan", "dahr"]},
    {"id": 77, "name": "Al-Mursalat", "english": "Those Sent Forth", "verses": 50, "aliases": ["mursalat", "thosesentforth", "theemissaries", "almursalat"]},
    {"id": 78, "name": "An-Naba", "english": "The Tidings", "verses": 40, "aliases": ["naba", "tidings", "greatnews", "thenews", "annaba"]},
    {"id": 79, "name": "An-Nazi'at", "english": "Those who drag forth", "verses": 46, "aliases": ["naziat", "thosewhodragforth", "thesnatchers", "thosewhoyankout", "annaziat"]},
    {"id": 80, "name": "'Abasa", "english": "He Frowned", "verses": 42, "aliases": ["abasa", "hefrowned", "frowned"]},
    {"id": 81, "name": "At-Takwir", "english": "The Overthrowing", "verses": 29, "aliases": ["takwir", "overthrowing", "foldingup", "theshrouding", "thefoldingup", "attakwir"]},
    {"id": 82, "name": "Al-Infitar", "english": "The Cleaving", "verses": 19, "aliases": ["infitar", "cleaving", "splitting", "thecleavingasunder", "alinfitar"]},
    {"id": 83, "name": "Al-Mutaffifin", "english": "The Defrauders", "verses": 36, "aliases": ["mutaffifin", "defrauders", "thosewhogiveshortmeasure", "almutaffifin"]},
    {"id": 84, "name": "Al-Inshiqaq", "english": "The Sundering", "verses": 25, "aliases": ["inshiqaq", "sundering", "splittingasunder", "thesplittingasunder", "alinshiqaq"]},
    {"id": 85, "name": "Al-Buruj", "english": "The Mansions of the Stars", "verses": 22, "aliases": ["buruj", "mansions", "constellations", "greatstars", "thestars", "alburuj"]},
    {"id": 86, "name": "At-Tariq", "english": "The Night-Comer", "verses": 17, "aliases": ["tariq", "nightcomer", "morningstar", "thenightcomer", "attariq"]},
    {"id": 87, "name": "Al-A'la", "english": "The Most High", "verses": 19, "aliases": ["ala", "mosthigh", "themosthigh", "alala"]},
    {"id": 88, "name": "Al-Ghashiyah", "english": "The Overwhelming", "verses": 26, "aliases": ["ghashiyah", "overwhelming", "theoverwhelming", "thepall", "alghashiyah"]},
    {"id": 89, "name": "Al-Fajr", "english": "The Dawn", "verses": 30, "aliases": ["fajr", "dawn", "thedawn", "alfajr"]},
    {"id": 90, "name": "Al-Balad", "english": "The City", "verses": 20, "aliases": ["balad", "city", "thecity", "theland", "albalad"]},
    {"id": 91, "name": "Ash-Shams", "english": "The Sun", "verses": 15, "aliases": ["shams", "sun", "thesun", "ashshams"]},
    {"id": 92, "name": "Al-Layl", "english": "The Night", "verses": 21, "aliases": ["layl", "night", "thenight", "allayl"]},
    {"id": 93, "name": "Ad-Duha", "english": "The Morning Hours", "verses": 11, "aliases": ["duha", "morninghours", "forenoon", "themorninghours", "adduha"]},
    {"id": 94, "name": "Ash-Sharh", "english": "The Relief", "verses": 8, "aliases": ["sharh", "relief", "solace", "openingup", "expansion", "ashsharh", "inshirah"]},
    {"id": 95, "name": "At-Tin", "english": "The Fig", "verses": 8, "aliases": ["tin", "fig", "thefig", "attin"]},
    {"id": 96, "name": "Al-'Alaq", "english": "The Clot", "verses": 19, "aliases": ["alaq", "clot", "germcell", "clingingspot", "read", "alalaq", "iqra"]},
    {"id": 97, "name": "Al-Qadr", "english": "The Power", "verses": 5, "aliases": ["qadr", "power", "decree", "nightofpower", "destiny", "alqadr"]},
    {"id": 98, "name": "Al-Bayyinah", "english": "The Clear Proof", "verses": 8, "aliases": ["bayyinah", "clearproof", "evidence", "theclearproof", "albayyinah"]},
    {"id": 99, "name": "Az-Zalzalah", "english": "The Earthquake", "verses": 8, "aliases": ["zalzalah", "earthquake", "theearthquake", "azzalzalah", "zilzal"]},
    {"id": 100, "name": "Al-'Adiyat", "english": "The Courser", "verses": 11, "aliases": ["adiyat", "courser", "chargers", "therunners", "aladiyat"]},
    {"id": 101, "name": "Al-Qari'ah", "english": "The Calamity", "verses": 11, "aliases": ["qariah", "calamity", "strikinghour", "disaster", "thestrikinghour", "alqariah"]},
    {"id": 102, "name": "At-Takathur", "english": "The Rivalry in World Increase", "verses": 8, "aliases": ["takathur", "rivalry", "worldincrease", "competition", "pilingup", "attakathur"]},
    {"id": 103, "name": "Al-'Asr", "english": "The Declining Day", "verses": 3, "aliases": ["asr", "decliningday", "time", "theafternoon", "alasr"]},
    {"id": 104, "name": "Al-Humazah", "english": "The Traducer", "verses": 9, "aliases": ["humazah", "traducer", "slanderer", "theslanderer", "alhumazah"]},
    {"id": 105, "name": "Al-Fil", "english": "The Elephant", "verses": 5, "aliases": ["fil", "elephant", "theelephant", "alfil"]},
    {"id": 106, "name": "Quraysh", "english": "Quraysh", "verses": 4, "aliases": ["quraysh", "koreish"]},
    {"id": 107, "name": "Al-Ma'un", "english": "The Small Kindnesses", "verses": 7, "aliases": ["maun", "smallkindnesses", "almsgiving", "assistance", "almaun"]},
    {"id": 108, "name": "Al-Kauthar", "english": "The Abundance", "verses": 3, "aliases": ["kauthar", "abundance", "plenty", "alkauthar"]},
    {"id": 109, "name": "Al-Kafirun", "english": "The Disbelievers", "verses": 6, "aliases": ["kafirun", "disbelievers", "theunbelievers", "alkafirun"]},
    {"id": 110, "name": "An-Nasr", "english": "The Divine Support", "verses": 3, "aliases": ["nasr", "support", "victory", "help", "annasr"]},
    {"id": 111, "name": "Al-Masad", "english": "The Palm Fiber", "verses": 5, "aliases": ["masad", "palmfiber", "lahab", "flame", "almasad"]},
    {"id": 112, "name": "Al-Ikhlas", "english": "The Sincerity", "verses": 4, "aliases": ["ikhlas", "sincerity", "purity", "monotheism", "alikhlas", "tauhid"]},
    {"id": 113, "name": "Al-Falaq", "english": "The Daybreak", "verses": 5, "aliases": ["falaq", "daybreak", "risingdawn", "alfalaq"]},
    {"id": 114, "name": "An-Nas", "english": "Mankind", "verses": 6, "aliases": ["nas", "mankind", "men", "people", "annas"]}
]
